openapi: 3.0.2
info:
  title: Games-API
  version: 1.0.0
  description: A brand new API with no content. Go nuts!

paths:
  /games:
    get:
      tags:
        - games
      summary: Get a list of all games
      description: Returns a list of all games in API
      responses:
        '200':
          description: List of games
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/game'
        '404':
          description: No games found
    post:
      tags:
        - games
      summary: Create a new game
      description: Adds a new game to the collection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new-game'
      responses:
        '201':
          description: Game successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/game'
        '400':
          description: Missing required parameters

  /games/{id}:
    get:
      tags:
        - games
      summary: Get game by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the game
      responses:
        '200':
          description: Full details of the game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/game'
        '404':
          description: Game not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    delete:
      tags:
        - games
      summary: Delete game by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the game to delete
      responses:
        '204':
          description: Game successfully deleted
        '404':
          description: Game not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

components:
  schemas:
    game:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: float
      example:
        id: 1
        name: Witcher 3
        price: 59.99

    new-game:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        price:
          type: number
          format: float
      example:
        name: Tetris
        price: 0.99

    error:
      type: object
      properties:
        error:
          type: string
      example:
        error: Game not found
